# Generated by Django 4.1.2 on 2022-12-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_add_profile_model"),
        ("users", "assign_interest_container"),
    ]

    operations = []
