version: "3.3"
services:
  nginx:
    build: ./nginx/
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/dishesz/assets/:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
     
    ports:
      - "80:80"
      - "443:443"
        
    depends_on: 
      - django
      - daphne 
    

  mysql-db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped
    environment:
       MYSQL_DATABASE: 'dishesz'
       MYSQL_USER: 'zeusgod-dev'
       MYSQL_PASSWORD: 'hgt.22-3dishesz'
       MYSQL_ROOT_PASSWORD: 'hgt.22-3dishesz'
      
    ports: 
       - "3306:3306" 
    expose: 
       - "3306"       
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

  
  django:
    build: ./dishesz/
    restart: always
    command: sh -c "python manage.py collectstatic --noinput && uwsgi --ini dishesz.ini && uwsgi --socket dishesz.sock --module dishesz.wsgi --chmod-socket=666"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/var/www/dishesz/assets/

    depends_on:
      - mysql-db 
  


  daphne:
    build: ./dishesz/
    command: bash -c "daphne -b 0.0.0.0 -p 8000 dishesz.asgi:application"
    links:
      - redis
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/var/www/dishesz/assets/


  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
    restart: on-failure

volumes:
  uwsgi_data:
  web_static:
  mysql_data: 