# Generated by Django 4.0.2 on 2022-11-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reffered', models.CharField(choices=[(1, 'follow request'), (2, 'following'), (3, 'saved recipe')], max_length=16)),
            ],
        ),
    ]
