# Generated by Django 4.0.2 on 2022-11-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/<function photo_path at 0x7f7733d4ad30>')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=24)),
                ('recipe_description', models.CharField(max_length=512)),
                ('prep_time', models.CharField(max_length=16)),
                ('cook_time', models.CharField(max_length=16)),
                ('directions', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField()),
                ('category', models.CharField(choices=[(1, 'Vegan'), (2, 'Spanish/Latin'), (3, 'Greek'), (4, 'American'), (5, 'Korean'), (6, 'Japanese'), (7, 'Chinese'), (8, 'Italian'), (8, 'Desserts'), (9, 'Smoothie')], default=(1, 'Vegan'), max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'HEAVILY DISLIKED'), (1, 'DISLIKED'), (3, 'FAIR'), (4, 'LIKE'), (5, 'LOVED')], default=(3, 'FAIR'))),
                ('description', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to='recipe.recipe')),
            ],
        ),
    ]
