# Generated by Django 4.1.2 on 2022-10-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="uploads/<function photo_path at 0x7f0bfd52c820>"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=24)),
                ("recipe_description", models.CharField(max_length=512)),
                ("prep_time", models.CharField(max_length=16)),
                ("cook_time", models.CharField(max_length=16)),
                ("directions", models.CharField(max_length=512)),
                ("created_on", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "HEAVILY DISLIKED"),
                            (1, "DISLIKED"),
                            (3, "FAIR"),
                            (4, "LIKE"),
                            (5, "LOVED"),
                        ],
                        default=(3, "FAIR"),
                    ),
                ),
                ("description", models.CharField(max_length=125)),
            ],
        ),
    ]
