# Generated by Django 4.0.2 on 2022-12-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(upload_to='uploads/<function photo_path at 0x7f3d33853d30>'),
        ),
    ]
