# Generated by Django 4.1.2 on 2022-10-31 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0003_alter_photo_photo_savedrecipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedrecipes",
            name="recipe",
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="uploads/<function photo_path at 0x7f9019ede8b0>"
            ),
        ),
        migrations.AlterField(
            model_name="savedrecipes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
