# Generated by Django 4.1.2 on 2022-11-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="uploads/<function photo_path at 0x7f42ff3321f0>"
            ),
        ),
    ]
