# Generated by Django 4.1.2 on 2022-10-31 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0004_remove_savedrecipes_recipe_alter_photo_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrecipes",
            name="recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_recipes",
                to="recipe.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="uploads/<function photo_path at 0x7efecfd0a8b0>"
            ),
        ),
        migrations.AlterField(
            model_name="savedrecipes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_saved_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
