# Generated by Django 4.1.2 on 2022-11-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="uploads/<function photo_path at 0x7f736ee20280>"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
