# Generated by Django 4.1.2 on 2022-11-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_alter_photo_photo_alter_savedrecipes_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="uploads/<function photo_path at 0x7f484be168b0>"
            ),
        ),
    ]
