# Generated by Django 4.1.2 on 2022-11-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_alter_photo_photo_alter_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="uploads/<function photo_path at 0x7f3fa040a280>"
            ),
        ),
        migrations.CreateModel(
            name="IngredientAvailableAt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=24)),
                (
                    "store_price",
                    models.DecimalField(decimal_places=2, default=None, max_digits=5),
                ),
                ("store_link", models.URLField(blank=True, max_length=300, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_at",
                        to="recipe.ingredient",
                    ),
                ),
            ],
        ),
    ]
