# Generated by Django 4.1.2 on 2023-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_alter_photo_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="src",
            field=models.ImageField(
                upload_to="uploads/<function photo_path at 0x7f356810c940>"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    (1, "Vegan"),
                    (2, "Spanish/Latin"),
                    (3, "Greek"),
                    (4, "American"),
                    (5, "Korean"),
                    (6, "Japanese"),
                    (7, "Chinese"),
                    (8, "Italian"),
                    (8, "Desserts"),
                    (9, "Smoothie"),
                ],
                default=1,
                max_length=65,
            ),
        ),
    ]
