# Generated by Django 4.0.2 on 2022-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_photo_photo_ingredientavailableat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='src',
            field=models.ImageField(null=True, upload_to='uploads/<function photo_path at 0x7f7105a0ac10>'),
        ),
    ]
